export enum SportsTypes {
    SET_LOADING = 'SPORTS/SET_LOADING',
    GET_ALL_SPORTS = 'SPORTS/GET_ALL_SPORTS',
    GET_SUCCESS_SPORTS = 'SPORTS/GET_SUCCESS_SPORTS',
    GET_FAILURE_SPORTS = 'SPORTS/GET_FAILURE_SPORTS',
    
    GET_LEAGUE_SPORTS = 'SPORTS/GET_LEAGUE_SPORTS',
    GET_SUCCESS_LEAGUE = 'SPORTS/GET_SUCCESS_LEAGUE',
    GET_FAILURE_LEAGUE = 'SPORTS/GET_FAILURE_LEAGUE',

    GET_TEAM_SPORTS = 'SPORTS/GET_TEAM_SPORTS',
    GET_SUCCESS_TEAM = 'SPORTS/GET_SUCCESS_TEAM',
    GET_FAILURE_TEAM = 'SPORTS/GET_FAILURE_TEAM',

   SPORTS_CLICKED = 'SPORTS/SPORTS_CLICKED',
   GENDER_CLICKED = 'SPORTS/GENDER_CLICKED',
   LEAGUE_CLICKED = 'SPORTS/LEAGUE_CLICKED',
   TEAM_CLICKED = 'SPORTS/TEAM_CLICKED',
   SET_GENDER = 'SPORTS/SET_GENDER',
   SET_LEAGUE = 'SPORTS/SET_LEAGUE',
   SET_TEAM = 'SPORTS/SET_TEAM',
   GET_SPORTS_LEAGUE = 'SPORTS/GET_SPORTS_LEAGUE',
   GET_SPORTS_TEAM = 'SPORTS/GET_SPORTS_TEAM',
}

export interface SportsState {
    readonly data: any[];
    readonly leagues: any[];
    readonly teams: any[];
    readonly followed: any[];
    readonly loading: boolean;
    readonly error: null;
}